export const mockDataTest = [
  {
    id: 1,
    image: "https://placehold.co/288x196",
    title: "Aceite motor Moly sintetico 5X30",
    description:
      "Aceite sintético de alta calidad para motores de automóviles, con nivel de acetatos 3x2",
    price: "$54,999",
    category: "Lubricantes",
    store: "AutoParts",
    brand: "ACME",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 2,
    title: "Filtro de aire para automóvil H239848",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aire de alto rendimiento para automóviles, mejora la eficiencia y la calidad del aire",
    price: "$2,499",
    category: "Filtros",
    store: "AutoRepuestos",
    brand: "XYZ",
    availability: {
      despacho: true,
      retiro: false,
    },
    rating: 1,
  },
  {
    id: 3,
    image: "https://placehold.co/288x196",
    title: "Pastillas de freno delanteras",
    description:
      "Pastillas de freno de alto rendimiento para automóviles y motociletas",
    price: "$1,999",
    category: "Frenos",
    store: "AutoServicio",
    brand: "123Brakes",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 4,
    title: "Batería para automóvil de alto rendimiento",
    image: "https://placehold.co/288x196",
    description:
      "Batería de larga duración y alto rendimiento para automóviles, confiable y de calidad",
    price: "$9,999",
    category: "Baterías",
    store: "Autopartes Express",
    brand: "PowerStart",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 5,
  },

  {
    id: 5,
    title: "Amortiguadores traseros",
    image: "https://placehold.co/288x196",
    description:
      "Amortiguadores de alta calidad para el sistema de suspensión de automóviles",
    price: "$6,499",
    category: "Suspensión",
    store: "AutoRepuestos",
    brand: "RideWell",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 6,
    title: "Líquido refrigerante para automóvil",
    image: "https://placehold.co/288x196",
    description:
      "Líquido refrigerante de larga duración para automóviles, protege el sistema genral",
    price: "$999",
    category: "Lubricantes",
    store: "AutoParts",
    brand: "CoolMax",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 7,
    title: "Filtro de combustible para automóvil",
    image: "https://placehold.co/288x196",
    description: "Filtro de combustible de alto rendimiento para automóviles.",
    price: "$1,199",
    category: "Filtros",
    store: "Repuestos Vehiculares",
    brand: "FuelGuard",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 8,
    title: "Llantas deportivas",
    image: "https://placehold.co/288x196",
    description: "Llantas deportivas de alto rendimiento para automóviles.",
    price: "$12,999",
    category: "Llantas",
    store: "Neumáticos Plus",
    brand: "SpeedMaster",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 9,
    title: "Kit de embrague para automóvil",
    image: "https://placehold.co/288x196",
    description: "Kit de embrague completo para automóviles .",
    price: "$8,599",
    category: "Transmisión",
    store: "Autopartes Express",
    brand: "ClutchPro",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 10,
    title: "Filtro de aceite para automóvil",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 11,
    title: "Filtro de aceite para automóvil",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 12,
    title: "Filtro de aceite para automóvil",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 13,
    title: "Filtro de aceite para automóvil",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 14,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 15,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 16,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 17,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 18,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 19,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 20,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 21,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 22,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 23,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 24,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 25,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 26,
    title: "Filtro de aceite para automóvil2",
    image: "https://placehold.co/288x196",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799",
    category: "Lubricantes",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
];

export const detail1_MockTest = {
  id: 1,
  title: "Aceite motor Moly sintetico 5X30",
  image: "https://placehold.co/288x196",
  description:
    "Aceite sintético de alta calidad para motores de automóviles, con nivel de acetatos 3x2",
  price: "$54,999",
  category: "Lubricantes",
  store: "AutoParts",
  brand: "ACME",
  availability: {
    despacho: true,
    retiro: true,
  },
  rating: 3,
};

export const detail2_MockTest = {
  id: 2,
  image: "https://placehold.co/288x196",
  title: "Aceite motor Moly sintetico 5X30",
  description:
    "Aceite sintético de alta calidad para motores de automóviles, con nivel de acetatos 3x2",
  price: "$54,999",
  category: "Lubricantes",
  store: "AutoParts",
  brand: "ACME",
  availability: {
    despacho: true,
    retiro: true,
  },
  rating: 3,
};

export const mockDataTestServices = [
  {
    id: 1,
    image: "https://placehold.co/288x196/87CEEB/FFF",

    title: "Servicio de Colorimetria",
    description:
      "Nuestros expertos aplicarán técnicas precisas para lograr una coloración uniforme y duradera.",
    price: "$54.999 - $80.000",
    category: "Lubricantes",
    store: "AutoParts",
    brand: "ACME",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 2,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Servicio de Mecania General",
    description:
      "Ajustes finos para asegurar que la sincronización sea estable y confiable",
    price: "$2,499 - $80.000",
    category: "Filtros",
    store: "AutoRepuestos",
    brand: "XYZ",
    availability: {
      despacho: true,
      retiro: false,
    },
    rating: 1,
  },
  {
    id: 3,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Servicio de pulida y pintura",
    description:
      "Pastillas de freno de alto rendimiento para automóviles y motociletas",
    price: "$1,999 - $80.000",
    category: "Frenos",
    store: "AutoServicio",
    brand: "123Brakes",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 4,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Batería para automóvil de alto rendimiento",
    description:
      "Batería de larga duración y alto rendimiento para automóviles, confiable y de calidad",
    price: "$9,999 - $80.000",
    category: "Baterías",
    store: "Autopartes Express",
    brand: "PowerStart",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 5,
  },

  {
    id: 5,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Amortiguadores traseros",
    description:
      "Amortiguadores de alta calidad para el sistema de suspensión de automóviles",
    price: "$6,499 - $80.000",
    category: "Suspensión",
    store: "AutoRepuestos",
    brand: "RideWell",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 6,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Líquido refrigerante para automóvil",
    description:
      "Líquido refrigerante de larga duración para automóviles, protege el sistema genral",
    price: "$999 - $80.000",
    category: "Refrigeración",
    store: "AutoParts",
    brand: "CoolMax",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 7,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Filtro de combustible para automóvil",
    description: "Filtro de combustible de alto rendimiento para automóviles.",
    price: "$1,199 - $80.000",
    category: "Filtros",
    store: "Repuestos Vehiculares",
    brand: "FuelGuard",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 8,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Llantas deportivas",
    description: "Llantas deportivas de alto rendimiento para automóviles.",
    price: "$12,999 - $80.000",
    category: "Llantas",
    store: "Neumáticos Plus",
    brand: "SpeedMaster",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 9,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Kit de embrague para automóvil",
    description: "Kit de embrague completo para automóviles .",
    price: "$8,599 - $80.000",
    category: "Transmisión",
    store: "Autopartes Express",
    brand: "ClutchPro",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 10,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Filtro de aceite para automóvil",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799 - $80.000",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 11,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Filtro de aceite para automóvil",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799 - $80.000",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 12,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Filtro de aceite para automóvil",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799 - $80.000",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
  {
    id: 13,
    image: "https://placehold.co/288x196/87CEEB/FFF",
    title: "Filtro de aceite para automóvil",
    description:
      "Filtro de aceite de alta calidad para automóviles, protege el motor.",
    price: "$799 - $80.000",
    category: "Filtros",
    store: "AutoServicio",
    brand: "PureFlow",
    availability: {
      despacho: true,
      retiro: true,
    },
    rating: 3,
  },
];
